--CAMPAIGN DETAILS--
SELECT CAMPAIGN.CAMPAIGN_CODE, CAMPAIGN.CAMPAIGN_NAME, PRODUCT.PRODUCT_NAME, CLIENT_COMPANY.COMPANY_NAME, STAFF.STAFF_NAME AS CAMPAIGN_MANAGER, CAMPAIGN.START_DATE, CAMPAIGN.END_DATE, CAMPAIGN.STATUS
FROM PRODUCT, CAMPAIGN, CLIENT_COMPANY, STAFF
WHERE PRODUCT.PRODUCT_ID = CAMPAIGN.PRODUCT_ID
AND CLIENT_COMPANY.COMPANY_ID = CAMPAIGN.COMPANY_ID
AND CAMPAIGN.CAMPAIGN_MANAGER_ID = STAFF.STAFF_NUM


--CAMPAIGN PLAN--
SELECT CLIENT_COMPANY.COMPANY_NAME, PRODUCT.PRODUCT_NAME, CAMPAIGN.CAMPAIGN_CODE, CAMPAIGN.CAMPAIGN_NAME, 
ADVERT.ADVERT_CODE, ADVERT.ADVERT_TYPE, ADVERT.TYPE_DESC, ADVERT.START_DATE, ADVERT.END_DATE
FROM CLIENT_COMPANY, PRODUCT, CAMPAIGN, ADVERT
WHERE CLIENT_COMPANY.COMPANY_ID = CAMPAIGN.COMPANY_ID
AND PRODUCT.PRODUCT_ID = CAMPAIGN.PRODUCT_ID
AND CAMPAIGN.CAMPAIGN_CODE = ADVERT.CAMPAIGN_CODE

--PLACEMENT LOCATION RECORD--
SELECT CAMPAIGN.CAMPAIGN_CODE, ADVERT.ADVERT_CODE, ADVERT.ADVERT_TYPE, PLACEMENT.PLACEMENT_CODE, CONTRACT.CONTRACT_REF_NO, CONTRACT.NAME, CONTRACT.CONTACT, CAMPAIGN.START_DATE, CAMPAIGN.END_DATE,
PLACEMENT_DETAILS.NO_OF_PAGES, PLACEMENT_DETAILS.NO_OF_EDITIONS, PLACEMENT_DETAILS.FREQUENCY, PLACEMENT_DETAILS.NO_OF_LEAFLETS, STAFF.STAFF_NAME
FROM CAMPAIGN, CONTRACT, PLACEMENT, PLACEMENT_DETAILS, ADVERT, STAFF
WHERE CAMPAIGN.CAMPAIGN_CODE = ADVERT.CAMPAIGN_CODE
AND PLACEMENT.ADVERT_CODE = ADVERT.ADVERT_CODE
AND PLACEMENT_DETAILS.CONTRACT_REF_NO = CONTRACT.CONTRACT_REF_NO
AND PLACEMENT_DETAILS.PLACEMENT_CODE = PLACEMENT.PLACEMENT_CODE


--HEADURA CAMPAIGN INVOLVEMENT--
SELECT CAMPAIGN.CAMPAIGN_CODE, CAMPAIGN.CAMPAIGN_NAME, CLIENT_COMPANY.COMPANY_NAME AS CLIENT_COMPANY, STAFF.STAFF_NUM, STAFF.STAFF_NAME, ROLE.ROLE_NAME AS ROLE, STAFF.STAFF_PHONE, 
STAFF.STAFF_FAX, STAFF.STAFF_EMAIL, PRODUCT.PRODUCT_NAME, 
CAMPAIGN.START_DATE, CAMPAIGN.END_DATE, CAMPAIGN.STATUS	 
FROM ROLE, STAFF, CAMPAIGN, PRODUCT, CLIENT_COMPANY
WHERE STAFF.STAFF_NUM = CAMPAIGN.CAMPAIGN_MANAGER_ID
AND PRODUCT.PRODUCT_ID = CAMPAIGN.PRODUCT_ID
AND CLIENT_COMPANY.COMPANY_ID = CAMPAIGN.COMPANY_ID
AND ROLE.ROLE_ID = STAFF.ROLE_ID

--CLIENT CAMPAIGN INVOLVEMENT--
SELECT CAMPAIGN_TEAM.CAMPAIGN_CODE,	CLIENT_STAFF.CL_STAFF_ID, CLIENT_STAFF.CL_STAFF_NAME, CLIENT_STAFF.CL_STAFF_POSITION, CLIENT_STAFF.CL_STAFF_PHONE, CLIENT_STAFF.CL_STAFF_EMAIL
FROM CAMPAIGN_TEAM INNER JOIN CLIENT_STAFF
ON CAMPAIGN_TEAM.CL_STAFF_ID1 = CLIENT_STAFF.CL_STAFF_ID
UNION
SELECT CAMPAIGN_TEAM.CAMPAIGN_CODE,	CLIENT_STAFF.CL_STAFF_ID, CLIENT_STAFF.CL_STAFF_NAME, CLIENT_STAFF.CL_STAFF_POSITION, CLIENT_STAFF.CL_STAFF_PHONE, CLIENT_STAFF.CL_STAFF_EMAIL
FROM CAMPAIGN_TEAM INNER JOIN CLIENT_STAFF
ON CAMPAIGN_TEAM.CL_STAFF_ID2 = CLIENT_STAFF.CL_STAFF_ID

--CLIENT MEETING ATTENDANCE--
SELECT MEET_ATTENDANCE.MEETING_ID AS MEETING_ID, CLIENT_STAFF.CL_STAFF_ID AS CL_STAFF_ID, CLIENT_STAFF.CL_STAFF_NAME AS CL_STAFF_NAME, CLIENT_STAFF.CL_STAFF_POSITION AS CL_STAFF_POSITION
FROM MEET_ATTENDANCE INNER JOIN CLIENT_STAFF
ON MEET_ATTENDANCE.CL_STAFF_ID1 = CLIENT_STAFF.CL_STAFF_ID
UNION
SELECT MEET_ATTENDANCE.MEETING_ID AS MEETING_ID, CLIENT_STAFF.CL_STAFF_ID AS CL_STAFF_ID, CLIENT_STAFF.CL_STAFF_NAME AS CL_STAFF_NAME, CLIENT_STAFF.CL_STAFF_POSITION AS CL_STAFF_POSITION
FROM MEET_ATTENDANCE INNER JOIN CLIENT_STAFF
ON MEET_ATTENDANCE.CL_STAFF_ID2 = CLIENT_STAFF.CL_STAFF_ID

-- HEADURA MEETING ATTENDANCE --
SELECT MEET_ATTENDANCE.MEETING_ID AS MEETING_ID, STAFF.STAFF_NUM AS STAFF_ID, STAFF.STAFF_NAME AS HEADURA_STAFF_NAME, STAFF.ROLE_ID
FROM MEET_ATTENDANCE INNER JOIN STAFF
ON MEET_ATTENDANCE.CAMPAIGN_MANAGER_ID = STAFF.STAFF_NUM
UNION
SELECT MEET_ATTENDANCE.MEETING_ID AS MEETING_ID, STAFF.STAFF_NUM AS STAFF_ID, STAFF.STAFF_NAME AS HEADURA_STAFF_NAME, STAFF.ROLE_ID
FROM MEET_ATTENDANCE INNER JOIN STAFF
ON MEET_ATTENDANCE.ACCOUNT_MANAGER_ID = STAFF.STAFF_NUM
UNION
SELECT MEET_ATTENDANCE.MEETING_ID AS MEETING_ID, STAFF.STAFF_NUM AS STAFF_ID, STAFF.STAFF_NAME AS HEADURA_STAFF_NAME, STAFF.ROLE_ID
FROM MEET_ATTENDANCE INNER JOIN STAFF
ON MEET_ATTENDANCE.GRAPHIC_DESIGNER_ID = STAFF.STAFF_NUM
ORDER BY MEETING_ID

--CAMPAIGN, ADVERT, PLACEMENT RELATION--
SELECT CAMPAIGN.CAMPAIGN_CODE, ADVERT.ADVERT_CODE, PLACEMENT.PLACEMENT_CODE
FROM CAMPAIGN, ADVERT, PLACEMENT
WHERE ADVERT.CAMPAIGN_CODE = CAMPAIGN.CAMPAIGN_CODE
AND PLACEMENT.ADVERT_CODE = ADVERT.ADVERT_CODE
ORDER BY CAMPAIGN.CAMPAIGN_CODE
